### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Jibiki
email: jibiki@martinp7r.com
description: Japanese Dictionary and Kanji Widgets
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jibiki.martinp7r.com" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: "#efeeff"
twitter_username: martinP7r
github_username: martinP7r
author: Martin
logo: assets/images/icon.png
twitter:
  username: martinP7r
social:
  name: Martin
  links:
    - https://twitter.com/martinP7r
    # - https://www.facebook.com/sandoche
    # - https://www.linkedin.com/in/sandoche
    # - https://plus.google.com/+SandocheADITTANE
    - https://github.com/martinP7r

languages: ["en"]
ampdir: amp

github: https://github.com/martinP7r/jibiki-pub

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
