name: Jibiki
description: Japanese Dictionary
full_description: 'A more complete description of the mobile app
<br>
<br>Current features:
<br>- Dictionary Search
<br>- Bookmarks'
# <br>- Daily Kanji Widget'
android: false
iOS: # TODO: link to appstore
web: false
screenshots:
  - 01-SearchList.png
  - 02-JMdictDetails.png
  - 03-bookmarks-screen.png
  - 04-downloads-screen.png
producthunt: false # https://telegra.ph/Replace-this-link-07-23
# companies:
  # - url: https://telegra.ph/Replace-this-link-07-23
  #   image: androidpolice.png
  # - url: https://telegra.ph/Replace-this-link-07-23
  #   image: producthunt.png
