name: Jibiki
description: Japanese Dictionary and Kanji Study Widget
full_description: 'A more complete description of the mobile app
<br>
<br>Current features:
<br>- Dictionary Search
<br>- Notes (= bookmarks)
<br>- Daily Kanji Widget'
android: false # https://telegra.ph/Replace-this-link-07-23
iOS: # https://telegra.ph/Replace-this-link-07-23
web: false # https://telegra.ph/Replace-this-link-07-23
screenshots:
  - SearchList.png
  - JMdictDetails.png
  - bookmarks-screen.png
  - downloads-screen.png
producthunt: false # https://telegra.ph/Replace-this-link-07-23
# companies:
  # - url: https://telegra.ph/Replace-this-link-07-23
  #   image: androidpolice.png
  # - url: https://telegra.ph/Replace-this-link-07-23
  #   image: producthunt.png
